version: '2'
services:

  vaper-server:
    container_name: vaper-server
    image: sysuhxn/vaper
    links:
      - neo4j
    ports:
      - 3000:3000
    networks:
      - esnet
    restart: unless-stopped
    
  neo4j:
    container_name: neo4j
    image: neo4j:3.3
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - esnet
    volumes:
      - neo4jdata:/data
    restart: unless-stopped

  elasticsearch01:
    image: elasticsearch:5
    container_name: elasticsearch01
    hostname: elasticsearch01
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    links:
      - vaper-server
    networks:
      - esnet
 
  kibana:
    image: kibana:5
    container_name: kibana
    hostname: kibana
    links:
      - elasticsearch01
    environment:
      ELASTICSEARCH_URL: http://elasticsearch01:9200
    ports:
      - 5601:5601
    networks:
      - esnet
    links:
      - vaper-server
  
  logstash:
    image: logstash:5
    container_name: logstash
    hostname: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    links:
      - elasticsearch01
    networks:
      - esnet
    command: ["-f", "/usr/share/logstash/pipeline/logstash.conf"]
    links:
      - vaper-server

  metricbeat01:
    image: athieriot/metricbeat
    container_name: metricbeat01
    hostname: metricbeat01
    volumes:
      - ./metricbeat.yml:/metricbeat/metricbeat.yml
    networks:
      - esnet
    links:
      - logstash
      - vaper-server

  metricbeat02:
    image: athieriot/metricbeat
    container_name: metricbeat02
    hostname: metricbeat02
    volumes:
      - ./metricbeat.yml:/metricbeat/metricbeat.yml
    networks:
      - esnet
    links:
      - logstash
      - vaper-server

volumes:
  esdata1:
    driver: local
  neo4jdata:
    driver: local

networks:
  esnet:
    driver: bridge

        