metricbeat.modules:
- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

output.logstash:
  hosts: ["logstash:5044"]

# output.kafka:
#   # initial brokers for reading cluster metadata
#   hosts: ["kafka:9092"]

#   # message topic selection + partitioning
#   topic: 'metric'
#   partition.round_robin:
#     reachable_only: false

#   required_acks: 1
#   compression: gzip
#   max_message_bytes: 1000000